// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAja3bYBkDJ7SHZXQ3Sqara8YZVSXHHBhA',
    appId: '1:543008005063:android:0a7b9926947ee090da97e2',
    messagingSenderId: '543008005063',
    projectId: 'ttt-by-ll',
    storageBucket: 'ttt-by-ll.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDuTv33MTfpNP2J0X_MHaxSzXwzAYG3cU',
    appId: '1:543008005063:web:637b81c9244df85cda97e2',
    messagingSenderId: '543008005063',
    projectId: 'ttt-by-ll',
    authDomain: 'ttt-by-ll.firebaseapp.com',
    storageBucket: 'ttt-by-ll.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAyRnOLO9KNSLySquY02JfX0ejgaB6JT_s',
    appId: '1:543008005063:ios:c21d02a8e30cbd04da97e2',
    messagingSenderId: '543008005063',
    projectId: 'ttt-by-ll',
    storageBucket: 'ttt-by-ll.firebasestorage.app',
    iosBundleId: 'com.example.ticTacToe',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAyRnOLO9KNSLySquY02JfX0ejgaB6JT_s',
    appId: '1:543008005063:ios:c21d02a8e30cbd04da97e2',
    messagingSenderId: '543008005063',
    projectId: 'ttt-by-ll',
    storageBucket: 'ttt-by-ll.firebasestorage.app',
    iosBundleId: 'com.example.ticTacToe',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDDuTv33MTfpNP2J0X_MHaxSzXwzAYG3cU',
    appId: '1:543008005063:web:ab9b76bc0eda1e8dda97e2',
    messagingSenderId: '543008005063',
    projectId: 'ttt-by-ll',
    authDomain: 'ttt-by-ll.firebaseapp.com',
    storageBucket: 'ttt-by-ll.firebasestorage.app',
  );

}